# name: E2E
# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Clean environment
#         run: |
#           rm -rf node_modules
#           rm -f package-lock.json

#       - name: Install npm dependencies
#         run: npm install
        
        

#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           command: npm run test
          

#       - name: Cypress Test Report
#         uses: actions/upload-artifact@v3
#         with: 
#           name: Mochaawesome HTML Report
#           path: cypress/reports/html

  # cypress-run-second:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
        
  #     - name: Clean environment
  #       run: |
  #         rm -rf node_modules
  #         rm -f package-lock.json

  #     - name: Install npm dependencies
  #       run: npm install

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         command: npm run test:lastname
  #         browser: chrome

  #     - name: Cypress Test Report
  #       uses: actions/upload-artifact@v3
        # 
  #       with: 
  #         name: Mochaawesome HTML Report2
  #         path: cypress/reports/html

  name: Cypress Tests

  on:
    push:
      branches:
        - main
  
  jobs:
    test:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '14'

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
  
        - name: Install dependencies
          run: npm install
  
        - name: Run Cypress tests
          run: |
            docker build --no-cache -t my-cypress-tests .
            docker run my-cypress-tests
  